#%RAML 1.0 DataType
type: object
properties:
  OrderAck:
    properties:
     countryCode :
       type: string
       required: false
     tostatus :
      type: string
      required: false
     inventoryChannel :
      type: string
      required: false
     creationTime: 
       type: string
       required: false
     lineId :
      type: string
      required: false
     requestedQuantity :
      type: string
      required: false
     state :
      type: string
      required: false
     order_num_count :
      type: string
      required: false
     creationDatetime:
       type: string
       required: false
          
     
           
          
    
      
    
      
      
  