###################################################################################
#   List all the service configurations in this file (both SOAP & REST)
###################################################################################
ws:
 NORA:
    dmandware:
        host: "staging-na01-kontoor.demandware.net"
        port: "443"
        basepath: "/s"
        clientid: "d1bb31f4-5b1e-4389-9c9a-35daaa7a695a"
        basepath2: "/dw"
        username: "vivek.chandran@appirio.com:Test@2020"    
        clientid: "d1bb31f4-5b1e-4389-9c9a-35daaa7a695a"
        granttype: "urn:demandware:params:oauth:grant-type:client-id:dwsid:dwsecuretoken"        
 EMEA:
    dmandware:
        host: "staging-eu01-kontoor.demandware.net"
        port: "443"
        basepath: "/s"
        clientid: "d1bb31f4-5b1e-4389-9c9a-35daaa7a695a"
        basepath2: "/dw"
        username: "vivek.chandran@appirio.com:Test@2020"
        granttype: "urn:demandware:params:oauth:grant-type:client-id:dwsid:dwsecuretoken"       
 http_config:
        port : "9010"
        host : "0.0.0.0"        
 bearertoken:
        host: "account.demandware.com"
        port: "443"
        basepath: "/dwsso"
        granttype: "client_credentials"
        clientid: "d1bb31f4-5b1e-4389-9c9a-35daaa7a695a"
        password: "MuleTest123$"  
 password: "MuleTest123$"     